openldap:
  image: osixia/openldap
  ports:
    - "389:389"
  volumes:
    - ./data/certs:/container/service/slapd/assets/certs
    - ./data/conf:/etc/ldap/slapd.d
    - ./data/data:/var/lib/ldap
  environment:
    - LDAP_ORGANISATION=EasyPi
    - LDAP_DOMAIN=ldap.easypi.pro
    - LDAP_ADMIN_PASSWORD=admin
    - LDAP_CONFIG_PASSWORD=config
    - LDAP_TLS_CA_CRT_FILENAME=ca.crt
    - LDAP_TLS_CRT_FILENAME=ldap.crt
    - LDAP_TLS_KEY_FILENAME=ldap.key
    # LDAP_TLS_ENFORCE=true
  restart: always

phpldapadmin:
  image: osixia/phpldapadmin
  ports:
    - "8080:80"
  environment:
    - PHPLDAPADMIN_LDAP_HOSTS=openldap
    - PHPLDAPADMIN_HTTPS=false
  links:
    - openldap
  restart: always
