splash:
  image: scrapinghub/splash:3.3
  command: --maxrss 4096 --max-timeout 300
  ports:
    - "8050:8050"
  volumes:
    - ./data/filters:/etc/splash/filters
    - ./data/js-profiles:/etc/splash/js-profiles
    - ./data/lua_modules:/etc/splash/lua_modules
    - ./data/proxy-profiles:/etc/splash/proxy-profiles
  mem_limit: 4608M
  restart: always
